version: "3.7"
services:
    web:
        build: .
        ports:
            - "5000:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        hostname: 'dbserver'
        environment:
            SA_PASSWORD: "<yourpw"
            ACCEPT_EULA: "Y"
        ports:
            - '1433:1433'
        expose:
            - 1433
        volumes:
            - /apps/sqldata:/var/opt/mssql
