apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: blogifier
  name: blogifier
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: blogifier
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: blogifier
    spec:
      containers:
      - image: hfamily6.azurecr.io/blogifier:v1
        imagePullPolicy: ""
        name: blogifier
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
      imagePullSecrets:
      - name: acr-auth
status: {}
